/* automatically generated by rust-bindgen 0.65.1 */

pub const QOA_MIN_FILESIZE: u32 = 16;
pub const QOA_MAX_CHANNELS: u32 = 8;
pub const QOA_SLICE_LEN: u32 = 20;
pub const QOA_SLICES_PER_FRAME: u32 = 256;
pub const QOA_FRAME_LEN: u32 = 5120;
pub const QOA_LMS_LEN: u32 = 4;
pub const QOA_MAGIC: u32 = 1903124838;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct qoa_lms_t {
    pub history: [::std::os::raw::c_int; 4usize],
    pub weights: [::std::os::raw::c_int; 4usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct qoa_desc {
    pub channels: ::std::os::raw::c_uint,
    pub samplerate: ::std::os::raw::c_uint,
    pub samples: ::std::os::raw::c_uint,
    pub lms: [qoa_lms_t; 8usize],
}
extern "C" {
    pub fn qoa_encode_header(
        qoa: *mut qoa_desc,
        bytes: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn qoa_encode_frame(
        sample_data: *const ::std::os::raw::c_short,
        qoa: *mut qoa_desc,
        frame_len: ::std::os::raw::c_uint,
        bytes: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn qoa_encode(
        sample_data: *const ::std::os::raw::c_short,
        qoa: *mut qoa_desc,
        out_len: *mut ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn qoa_max_frame_size(qoa: *mut qoa_desc) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn qoa_decode_header(
        bytes: *const ::std::os::raw::c_uchar,
        size: ::std::os::raw::c_int,
        qoa: *mut qoa_desc,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn qoa_decode_frame(
        bytes: *const ::std::os::raw::c_uchar,
        size: ::std::os::raw::c_uint,
        qoa: *mut qoa_desc,
        sample_data: *mut ::std::os::raw::c_short,
        frame_len: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn qoa_decode(
        bytes: *const ::std::os::raw::c_uchar,
        size: ::std::os::raw::c_int,
        file: *mut qoa_desc,
    ) -> *mut ::std::os::raw::c_short;
}
extern "C" {
    pub fn qoa_write(
        filename: *const ::std::os::raw::c_char,
        sample_data: *const ::std::os::raw::c_short,
        qoa: *mut qoa_desc,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qoa_read(
        filename: *const ::std::os::raw::c_char,
        qoa: *mut qoa_desc,
    ) -> *mut ::std::os::raw::c_void;
}
