/* automatically generated by rust-bindgen 0.65.1 */

#![allow(dead_code)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct qoa_lms_t {
    pub history: [::std::os::raw::c_int; 4usize],
    pub weights: [::std::os::raw::c_int; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct qoa_desc {
    pub channels: ::std::os::raw::c_uint,
    pub samplerate: ::std::os::raw::c_uint,
    pub samples: ::std::os::raw::c_uint,
    pub lms: [qoa_lms_t; 8usize],
    pub error: f64,
}
extern "C" {
    pub fn qoa_lms_predict(lms: *mut qoa_lms_t) -> ::std::os::raw::c_int;
    pub fn qoa_lms_update(
        lms: *mut qoa_lms_t,
        sample: ::std::os::raw::c_int,
        residual: ::std::os::raw::c_int,
    );
    pub fn qoa_encode_header(
        qoa: *mut qoa_desc,
        bytes: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_uint;
    pub fn qoa_encode_frame(
        sample_data: *const ::std::os::raw::c_short,
        qoa: *mut qoa_desc,
        frame_len: ::std::os::raw::c_uint,
        bytes: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_uint;
    pub fn qoa_encode(
        sample_data: *const ::std::os::raw::c_short,
        qoa: *mut qoa_desc,
        out_len: *mut ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void;
    pub fn qoa_decode_header(
        bytes: *const ::std::os::raw::c_uchar,
        size: ::std::os::raw::c_int,
        qoa: *mut qoa_desc,
    ) -> ::std::os::raw::c_uint;
    pub fn qoa_decode_frame(
        bytes: *const ::std::os::raw::c_uchar,
        size: ::std::os::raw::c_uint,
        qoa: *mut qoa_desc,
        sample_data: *mut ::std::os::raw::c_short,
        frame_len: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
    pub fn qoa_decode(
        bytes: *const ::std::os::raw::c_uchar,
        size: ::std::os::raw::c_int,
        file: *mut qoa_desc,
    ) -> *mut ::std::os::raw::c_short;
    pub fn qoaconv_wav_write(
        path: *const ::std::os::raw::c_char,
        sample_data: *mut ::std::os::raw::c_short,
        desc: *mut qoa_desc,
    ) -> ::std::os::raw::c_int;
    pub fn qoaconv_wav_read(
        path: *const ::std::os::raw::c_char,
        desc: *mut qoa_desc,
    ) -> *mut ::std::os::raw::c_short;
}
