[package]
name = "qoar"
version = "0.1.0"
edition = "2021"

[features]
default = [ "conv" ]
conv = [ "dep:symphonia" ]

[dependencies]
amplify_derive = "2.11.3"
symphonia = { version = "0.5.2", optional = true }
